### ISSUE TITLE
MT0013: Script for merging the realign (2)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/mt-aligner-prep-tool#19]
### Description
There is an existing package called mt-aligner-prep-tool, which is used to align tibetan and english text files containing in github organization "MonlamAI". Currently, the aligner and the realigner script is working, but when we want to merge the realigner branch to main branch, merge conflict issue is coming. So this problem we must solve.

### Completion Criteria

- Successfully merging a branch from a test TMxxxx repo successfully with the main without any issues.
- Successfully able to run the aligner script from the bdrc server and no human intervention within the process.

### Implementation Plan

![Image](https://github.com/OpenPecha/mt-aligner-prep-tool/assets/52460417/bcde5a9f-fe05-4b9b-9bb0-17fc0f6a2074)

Subtask:

- [x] script to merge the git branch to main
- [x] test the script
- [x] suppress the unneccessary outputs in pipeline
- [x] update the script in server
- [x] test the aligner script from the server

**Comment by tenzin3** [comment]
the approach to merge the branch with main changed since there were merge conflit for TMxx-bo.txt and TMxx-en.txt files too, so in the new approach, where ever there is a merge conflict, we choose the incoming changes(from new branch) automatically .
