### ISSUE TITLE
MT0022: Align new repos

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/mt-aligner-prep-tool#27]
## Description 
We have list of new repos and we need to realign them with our [mt-prep-tool](https://github.com/OpenPecha/mt-aligner-prep-tool
)script to create training data for machine translation.

## Expected output
Realigned new TM repos.
Relaigned new TM repos list(ids).

## Implementation Steps

- [x] check if bo en repo exits
- [x] check if tm repo exists
- [x] modify script to check aspiration-ai for bo en 
- [x] update the tokenizer
- [x] optimize chunking process
- [x] run aligner script
- [x] give a report

**Comment by tenzin3** [comment]
Number of ids: 354
Number of unique ids: 347

**Comment by tenzin3** [comment]
repos with no tm :> 155 (out of 347)

0443, 4924, 4238, 2730, 4806, 2749, 1854, 1732, 4753, 2199, 0043, 4667, 7615, 0151, 2909, 0784, 1711, 4876, 1560, 1647, 4893, 7671, 4657, 7598, 4882, 0052, 1385, 2751, 1353, 2349, 1844, 1743, 0868, 2726, 4888, 7597, 3082, 1858, 1513, 0116, 4907, 2354, 4883, 1849, 1725, 0667, 3793, 2906, 5589, 4650, 2282, 4672, 1806, 2998, 0005, 4879, 7604, 0045, 2972, 2277, 2736, 0503, 3257, 0544, 0754, 0094, 0109, 1688, 7006, 1101, 4989, 4535, 4639, 3466, 2986, 2908, 4610, 2150, 1742, 4680, 4372, 2733, 0619, 4669, 0086, 4649, 2728, 1730, 2768, 0107, 0563, 4814, 2904, 2416, 0596, 0079, 7003, 2244, 2963, 0881, 1737, 3951, 0178, 4920, 5591, 4636, 1882, 0647, 0007, 0452, 1876, 2321, 4630, 1439, 0505, 0607, 0071, 4683, 0745, 2744, 4603, 7501, 4441, 3724, 0569, 2427, 0555, 7500, 7593, 4600, 4614, 4877, 2734, 1722, 4591, 1723, 4555, 0463, 1809, 3694, 1041, 3690, 0621, 2739, 2453, 3003, 3016, 0220, 3255, 1539, 1726, 0430, 2771, 1659, 7829

**Comment by tenzin3** [comment]
@TenzinGayche  
**Searched from MonlamAI and aspiration-ai repo**

ids from 155 list with no BO repo:
7671, 2998, 0178, 1439

ids from 155 list with no EN repo:
1439

**Comment by TenzinGayche** [comment]
Passang comments on the following issues 
![Image](https://github.com/user-attachments/assets/3d8d77d8-6cd4-49c6-9d76-95383f76974c)

**Comment by tenzin3** [comment]
@kaldan007 @TenzinGayche,

When running the script on the BDRC server, the process keeps getting killed. This issue might be due to other processes currently running on the server. If many processes are running consistenly in bdrc server from recent period, we may need a server with more memory.

Currently, the script is being run on a personal PC.

**Comment by tenzin3** [comment]
@TenzinGayche 
from from 151 ids to align and having proper bo and en ids:

**Properly Aligned(128):>**
0443,  4924,  4238,  2730,  2749,  1732,  0043,  4667,  7615,  0151,  2909,  1711,  4876,  1560,  1647,  4893,  7598,  4882,  0052,  1385,  2751,  2349,  1844,  1743,  0868,  2726,  4888,  7597,  3082,  1858,  1513,  0116,  4907,  2354,  4883,  1849,  1725,  0667,  2906,  5589,  4650,  2282,  4672,  1806,  0005,  4879,  0045,  2972,  2277,  2736,  0503,  3257,  0544,  0754,  0094,  0109,  1101,  4989,  4535,  2908,  4610,  2150,  1742,  4680,  2733,  0619,  4669,  0086,  4649,  2728,  1730,  2768,  0107,  2416,  0079,  7003,  2244,  2963,  0881,  1737,  3951,  4920,  4636,  1882,  0647,  0007,  0452,  1876,  4630,  0505,  0071,  4683,  0745,  4603,  7501,  0569,  2427,  0555,  7500,  7593,  4600,  4614,  4877,  2734,  1722,  1723,  4555,  0463,  1809,  3694,  1041,  3690,  0621,  2739,  2453,  3016,  3255,  1539,  1726,  0430,  2771,  1659,  7829

**Repo with no proper txt file(28):>**
4806, 1854, 4753, 2199, 0784, 4657, 1353, 3793, 7604, 1688, 7006, 4639, 3466, 2986, 4372, 0563, 4814, 2904, 0596, 5591, 2321, 0607, 2744, 4441, 3724, 4591, 3003, 0220,
